site_name: Cheetsheet for Software Engineer
site_url: https://cheatsheet.hackerphysics.com

theme:
    name: material
    # logo: images/python.png
    # favicon: images/python.png
    language: 'zh'
    features:
      - navigation.expand
      - navigation.top
      - navigation.tabs
      - search.suggest
      - toc.integrate
      - content.code.annotate


nav:
- 'Windows': 'windows.md'
- 'Linux': 'linux.md'
- 'Python': 'python.md'
- 'C++': 'c++.md'
- 'C#': 'csharp.md'
- 'VSCode': 'vscode.md'
- 'Vim': 'vim.md'

plugins:
    # - with-pdf

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js